'use strict';

/**
 * Resonance Engine — evaluates network-wide social reactions
 * when a new NIT registers on the network.
 *
 * Returns reaction set + any new feed posts generated by RESONATE events.
 */

const registry = require('./nit-registry');

function evaluateNetworkReaction(new_node_id) {
  const allNodes = registry.getAllNodes();
  const reactions = [];
  const newPosts  = [];

  for (const node of allNodes) {
    if (node.node_id === new_node_id) continue;
    if (!node.online) continue;

    const { reaction, score } = registry.evaluateReaction(node.node_id, new_node_id);
    reactions.push({ from: node.node_id, to: new_node_id, reaction, score });

    if (reaction === 'RESONATE') {
      const connected = registry.establishConnection(node.node_id, new_node_id, score);
      if (connected) {
        const post = registry.addPost({
          node_id:         node.node_id,
          type:            'SOCIAL_SIGNAL',
          to:              new_node_id,
          resonance_score: score,
          msg:             'SYNC_REQUEST',
        });
        newPosts.push(post);
      }
    }
  }

  return { reactions, newPosts };
}

module.exports = { evaluateNetworkReaction };
