'use strict';

/**
 * Phase 28 — ZK Compliance Prover/Verifier (NIT-IN side)
 *
 * Wraps snarkjs Groth16 for the compliance_batch circuit.
 * On NIT-IN, this module is used ONLY for verification (re-run groth16.verify
 * against incoming proof + public signals from the Arduino Linux core).
 *
 * The Arduino Linux core is the prover — it calls fullProve locally, then
 * POSTs the proof + public signals to POST /api/audit/zk-commit.
 *
 * Artifacts (wasm, zkey, verification_key.json) are generated by
 * scripts/zk_setup.sh and must be present in circuits/build/ before
 * ZK routes are active. If artifacts are absent the routes return 503.
 */

const snarkjs = require('snarkjs');
const fs      = require('fs');
const path    = require('path');

const BUILD_DIR = path.join(__dirname, '../circuits/build');
const VKEY_PATH = path.join(BUILD_DIR, 'verification_key.json');

// Lazy-loaded — null until first call to _loadVKey()
let _vkey = null;
let _artifactsMissing = false; // cached "not found" flag to avoid repeated disk checks

// ── Internal ────────────────────────────────────────────────────────────────

function _loadVKey() {
  if (_vkey) return _vkey;
  if (_artifactsMissing) return null;
  if (!fs.existsSync(VKEY_PATH)) {
    console.warn('[ZK] verification_key.json not found — run scripts/zk_setup.sh');
    _artifactsMissing = true;
    return null;
  }
  try {
    _vkey = JSON.parse(fs.readFileSync(VKEY_PATH, 'utf8'));
    console.log('[ZK] Verification key loaded from', VKEY_PATH);
    return _vkey;
  } catch (err) {
    console.error('[ZK] Failed to parse verification_key.json:', err.message);
    _artifactsMissing = true;
    return null;
  }
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * Returns true if the verification key artifact is present and loadable.
 * Prover artifacts (wasm + zkey) are only needed on the Arduino Linux core.
 */
function artifactsReady() {
  return !!_loadVKey();
}

/**
 * Verify a Groth16 proof produced by the Arduino Linux core.
 *
 * @param {object} proof        - snarkjs proof object ({ pi_a, pi_b, pi_c, protocol, curve })
 * @param {string[]} publicSignals - array of decimal-string field elements (public inputs + output)
 *   Expected order (matches circuit main component declaration):
 *     [0] principle_id_hash
 *     [1] batch_time_start
 *     [2] batch_time_end
 *     [3] declared_event_count
 *     [4] declared_blocked_count
 *     [5] batch_commitment  ← circuit output, also a public signal
 *
 * @returns {Promise<boolean>}
 */
async function verifyCompliance(proof, publicSignals) {
  const vkey = _loadVKey();
  if (!vkey) throw new Error('ZK artifacts not built — run scripts/zk_setup.sh');
  return snarkjs.groth16.verify(vkey, publicSignals, proof);
}

/**
 * Parse and validate the shape of an incoming zk-commit body.
 * Returns { ok, error } — does NOT do cryptographic verification.
 */
function validateCommitBody(body) {
  if (!body || typeof body !== 'object') return { ok: false, error: 'body required' };
  const { proof, public_signals, metadata } = body;
  if (!proof || typeof proof !== 'object')           return { ok: false, error: 'proof object required' };
  if (!Array.isArray(public_signals) || public_signals.length < 6)
                                                     return { ok: false, error: 'public_signals[] with ≥6 entries required' };
  if (!metadata || typeof metadata !== 'object')     return { ok: false, error: 'metadata object required' };
  const { principle_id, arduino_node_id } = metadata;
  if (!principle_id)    return { ok: false, error: 'metadata.principle_id required' };
  if (!arduino_node_id) return { ok: false, error: 'metadata.arduino_node_id required' };
  return { ok: true };
}

module.exports = { artifactsReady, verifyCompliance, validateCommitBody };
